from __future__ import annotations

from pathlib import Path
from typing import Optional, Union

import torch
from torch import nn
from torchvision.io import read_video


def load_video_frames(video_path: Union[str, Path]) -> torch.Tensor:
    """
    Load a Dynamicrafter video and convert it to a tensor suitable for VGGT.

    Args:
        video_path: Path to an input video file (e.g. an mp4 produced by Interpose/Dynamicrafter).

    Returns:
        torch.Tensor with shape [S, 3, H, W] in range [0, 1], where:
            - S: number of frames
            - H, W: spatial resolution, center-cropped so both are divisible by 14.
    """
    video_path = Path(video_path)
    if not video_path.is_file():
        raise FileNotFoundError(f"Video not found: {video_path}")

    # read_video returns: frames [T, H, W, C] in uint8
    frames, _, _ = read_video(str(video_path), pts_unit="sec")
    if frames.numel() == 0:
        raise ValueError(f"No frames read from video: {video_path}")

    # Convert to [S, 3, H, W] float32 in [0, 1]
    frames = frames.permute(0, 3, 1, 2).float() / 255.0

    # Ensure height/width are divisible by 14 (patch size of VGGT).
    # We do a simple center-crop to the nearest multiple-of-14 resolution.
    _, _, H, W = frames.shape
    patch_size = 14
    new_H = H - (H % patch_size)
    new_W = W - (W % patch_size)

    if new_H <= 0 or new_W <= 0:
        raise ValueError(
            f"Video resolution too small for patch size {patch_size}: got H={H}, W={W}"
        )

    if new_H != H or new_W != W:
        top = (H - new_H) // 2
        left = (W - new_W) // 2
        frames = frames[:, :, top : top + new_H, left : left + new_W]

    return frames


@torch.no_grad()
def run_vggt3d_first_inference(
    model: nn.Module,
    video_path: Union[str, Path],
    device: Optional[torch.device] = None,
) -> dict:
    """
    Run the first VGGT3D inference on a Dynamicrafter video.

    This corresponds to Step 1 in the VGGT4D-style pipeline:
    feeding the full video sequence through VGGT to obtain
    camera poses, depth maps, and 3D scene predictions.

    Args:
        model: A VGGT-style model (e.g. `vggt.models.vggt.VGGT` or a wrapper)
               that accepts images with shape [S, 3, H, W] or [B, S, 3, H, W]
               and returns a predictions dict.
        video_path: Path to the input video generated by Dynamicrafter.
        device: Optional torch.device. If None, chooses CUDA when available.

    Returns:
        The predictions dict from the model forward pass.
        (e.g. keys like "pose_enc", "depth", "world_points", etc.)
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    frames = load_video_frames(video_path).to(device)  # [S, 3, H, W]
    model = model.to(device)
    model.eval()

    predictions = model(frames)
    return predictions

